# Generated by Django 4.0.4 on 2022-05-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrabajoFinalApp', '0002_category_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
